
//$Id$

package net.sf.persist.tests.common;

import net.sf.persist.annotations.Column;
import net.sf.persist.annotations.Table;

@Table(name="simple")
public class Simple06 {

	private long id;
	private String stringCol;
	private long intCol;

	// only setter annotated -- ok
	public long getId() { return id; }
	@Column(autoGenerated=true)
	public void setId(long id) { this.id = id; }

	// annotations for getter and setter are the same -- ok
	@Column(name="string_col", autoGenerated=false)
	public String getStringCol() { return stringCol; }
	@Column(autoGenerated=false, name="string_col")
	public void setStringCol(String stringCol) { this.stringCol = stringCol; }

	// annotations for getter and setter are different -- will blow
	@Column(name="int_col")
	public long getIntCol() { return intCol; }
	@Column(name="col_int")
	public void setIntCol(long intCol) { this.intCol = intCol; }

}

