
//$Id$

package net.sf.persist.tests.common;

import net.sf.persist.annotations.Column;
import net.sf.persist.annotations.NoColumn;
import net.sf.persist.annotations.Table;

@Table(name="simple")
public class Simple07 {

	private long id;
	//private String stringCol;
	private long intCol;

	@Column(autoGenerated=true)
	public long getId() { return id; }
	public void setId(long id) { this.id = id; }

	@NoColumn
	public String getHelloWorld() { return "hello world"; }
	public void setHelloWorld(String stringCol) { /* do nothing */ }

	public long getIntCol() { return intCol; }
	public void setIntCol(long intCol) { this.intCol = intCol; }

	// won't find a match for foo
	public String getFoo() { return "foo"; }
	public void setFoo(String foo) { /* do nothing */ }
	
}

